// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/auth.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/auth.proto.
 */
export const file_dox_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChFkb3gvdjEvYXV0aC5wcm90bxIGZG94LnYxIhMKEVNlcnZlckluZm9SZXF1ZXN0ImMKElNlcnZlckluZm9SZXNwb25zZRIRCgloYXNfdXNlcnMYASABKAgSGQoRcmVnaXN0cmF0aW9uX29wZW4YAiABKAgSDwoHdmVyc2lvbhgDIAEoCRIOCgZjb21taXQYBCABKAkiYwoPUmVnaXN0ZXJSZXF1ZXN0EhEKCXVzZXJfbmFtZRgBIAEoCRITCgtkZXZpY2VfbmFtZRgCIAEoCRIYCgtpbnZpdGVfY29kZRgDIAEoCUgAiAEBQg4KDF9pbnZpdGVfY29kZSJ7ChBSZWdpc3RlclJlc3BvbnNlEg0KBXRva2VuGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSEQoJdXNlcl9uYW1lGAMgASgJEgwKBHJvbGUYBCABKAkSEQoJZGV2aWNlX2lkGAUgASgJEhMKC2RldmljZV9uYW1lGAYgASgJIigKGFJlZGVlbVBhaXJpbmdDb2RlUmVxdWVzdBIMCgRjb2RlGAEgASgJInYKGVJlZGVlbVBhaXJpbmdDb2RlUmVzcG9uc2USDQoFdG9rZW4YASABKAkSEQoJZGV2aWNlX2lkGAIgASgJEhMKC2RldmljZV9uYW1lGAMgASgJEg8KB3VzZXJfaWQYBCABKAkSEQoJdXNlcl9uYW1lGAUgASgJMsMCCgtBdXRoU2VydmljZRJhCgpTZXJ2ZXJJbmZvEhkuZG94LnYxLlNlcnZlckluZm9SZXF1ZXN0GhouZG94LnYxLlNlcnZlckluZm9SZXNwb25zZSIcgtPkkwIWEhQvdjEvYXV0aC9zZXJ2ZXItaW5mbxJbCghSZWdpc3RlchIXLmRveC52MS5SZWdpc3RlclJlcXVlc3QaGC5kb3gudjEuUmVnaXN0ZXJSZXNwb25zZSIcgtPkkwIWOgEqIhEvdjEvYXV0aC9yZWdpc3RlchJ0ChFSZWRlZW1QYWlyaW5nQ29kZRIgLmRveC52MS5SZWRlZW1QYWlyaW5nQ29kZVJlcXVlc3QaIS5kb3gudjEuUmVkZWVtUGFpcmluZ0NvZGVSZXNwb25zZSIagtPkkwIUOgEqIg8vdjEvYXV0aC9yZWRlZW1CNlo0Z2l0aHViLmNvbS9saW4tc25vdy9kb3gvYXBwcy9zZXJ2ZXIvZ2VuL2RveC92MTtkb3h2MWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * @generated from message dox.v1.ServerInfoRequest
 */
export type ServerInfoRequest = Message<"dox.v1.ServerInfoRequest"> & {
};

/**
 * Describes the message dox.v1.ServerInfoRequest.
 * Use `create(ServerInfoRequestSchema)` to create a new message.
 */
export const ServerInfoRequestSchema: GenMessage<ServerInfoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 0);

/**
 * @generated from message dox.v1.ServerInfoResponse
 */
export type ServerInfoResponse = Message<"dox.v1.ServerInfoResponse"> & {
  /**
   * True once the server has at least one registered user. When false, the next
   * Register call promotes the caller to owner regardless of invite/registration
   * policy.
   *
   * @generated from field: bool has_users = 1;
   */
  hasUsers: boolean;

  /**
   * Mirrors the registration_open server setting. When true, Register works
   * without an invite code (only meaningful once has_users is true).
   *
   * @generated from field: bool registration_open = 2;
   */
  registrationOpen: boolean;

  /**
   * Server build identity, surfaced unauthenticated so a CLI can warn on
   * CLI/server version skew before login.
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * Short commit sha for the running server build. May carry a "-dirty"
   * suffix for local builds.
   *
   * @generated from field: string commit = 4;
   */
  commit: string;
};

/**
 * Describes the message dox.v1.ServerInfoResponse.
 * Use `create(ServerInfoResponseSchema)` to create a new message.
 */
export const ServerInfoResponseSchema: GenMessage<ServerInfoResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 1);

/**
 * @generated from message dox.v1.RegisterRequest
 */
export type RegisterRequest = Message<"dox.v1.RegisterRequest"> & {
  /**
   * Display name for the new user. Must be unique across the server.
   *
   * @generated from field: string user_name = 1;
   */
  userName: string;

  /**
   * Name for the first device (e.g. "laptop", "phone").
   *
   * @generated from field: string device_name = 2;
   */
  deviceName: string;

  /**
   * Required when registration is closed and the users table is non-empty.
   *
   * @generated from field: optional string invite_code = 3;
   */
  inviteCode?: string | undefined;
};

/**
 * Describes the message dox.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 2);

/**
 * @generated from message dox.v1.RegisterResponse
 */
export type RegisterResponse = Message<"dox.v1.RegisterResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 3;
   */
  userName: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: string device_id = 5;
   */
  deviceId: string;

  /**
   * @generated from field: string device_name = 6;
   */
  deviceName: string;
};

/**
 * Describes the message dox.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 3);

/**
 * @generated from message dox.v1.RedeemPairingCodeRequest
 */
export type RedeemPairingCodeRequest = Message<"dox.v1.RedeemPairingCodeRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message dox.v1.RedeemPairingCodeRequest.
 * Use `create(RedeemPairingCodeRequestSchema)` to create a new message.
 */
export const RedeemPairingCodeRequestSchema: GenMessage<RedeemPairingCodeRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 4);

/**
 * @generated from message dox.v1.RedeemPairingCodeResponse
 */
export type RedeemPairingCodeResponse = Message<"dox.v1.RedeemPairingCodeResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string device_id = 2;
   */
  deviceId: string;

  /**
   * @generated from field: string device_name = 3;
   */
  deviceName: string;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 5;
   */
  userName: string;
};

/**
 * Describes the message dox.v1.RedeemPairingCodeResponse.
 * Use `create(RedeemPairingCodeResponseSchema)` to create a new message.
 */
export const RedeemPairingCodeResponseSchema: GenMessage<RedeemPairingCodeResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 5);

/**
 * AuthService hosts the public (unauthenticated) RPCs:
 *   - ServerInfo lets a client probe the server before logging in, so the
 *     onboarding UI can pick the right branch (first-user / open registration /
 *     invite-required) without exposing concepts to the user.
 *   - Register creates a user. The first-ever Register on an empty server makes
 *     the caller the owner. Subsequent Registers require either a valid invite
 *     code or registration_open=true.
 *   - RedeemPairingCode is for an existing user adding another device to their
 *     own account (no new user is created).
 *
 * @generated from service dox.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc dox.v1.AuthService.ServerInfo
   */
  serverInfo: {
    methodKind: "unary";
    input: typeof ServerInfoRequestSchema;
    output: typeof ServerInfoResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.AuthService.RedeemPairingCode
   */
  redeemPairingCode: {
    methodKind: "unary";
    input: typeof RedeemPairingCodeRequestSchema;
    output: typeof RedeemPairingCodeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_auth, 0);

