// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/auth.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/auth.proto.
 */
export const file_dox_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChFkb3gvdjEvYXV0aC5wcm90bxIGZG94LnYxIhMKEVNlcnZlckluZm9SZXF1ZXN0IqgBChJTZXJ2ZXJJbmZvUmVzcG9uc2USEQoJaGFzX3VzZXJzGAEgASgIEhkKEXJlZ2lzdHJhdGlvbl9vcGVuGAIgASgIEg8KB3ZlcnNpb24YAyABKAkSDgoGY29tbWl0GAQgASgJEhMKC3NlcnZlcl9uYW1lGAUgASgJEhoKEnNlcnZlcl9kZXNjcmlwdGlvbhgGIAEoCRISCgpvd25lcl9uYW1lGAcgASgJIsIBCg9SZWdpc3RlclJlcXVlc3QSEQoJdXNlcl9uYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhgKC2ludml0ZV9jb2RlGAMgASgJSACIAQESGAoLc2VydmVyX25hbWUYBCABKAlIAYgBARIfChJzZXJ2ZXJfZGVzY3JpcHRpb24YBSABKAlIAogBAUIOCgxfaW52aXRlX2NvZGVCDgoMX3NlcnZlcl9uYW1lQhUKE19zZXJ2ZXJfZGVzY3JpcHRpb24iUwoQUmVnaXN0ZXJSZXNwb25zZRINCgV0b2tlbhgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhEKCXVzZXJfbmFtZRgDIAEoCRIMCgRyb2xlGAQgASgJIjMKDExvZ2luUmVxdWVzdBIRCgl1c2VyX25hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiUAoNTG9naW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhEKCXVzZXJfbmFtZRgDIAEoCRIMCgRyb2xlGAQgASgJMp4CCgtBdXRoU2VydmljZRJhCgpTZXJ2ZXJJbmZvEhkuZG94LnYxLlNlcnZlckluZm9SZXF1ZXN0GhouZG94LnYxLlNlcnZlckluZm9SZXNwb25zZSIcgtPkkwIWEhQvdjEvYXV0aC9zZXJ2ZXItaW5mbxJbCghSZWdpc3RlchIXLmRveC52MS5SZWdpc3RlclJlcXVlc3QaGC5kb3gudjEuUmVnaXN0ZXJSZXNwb25zZSIcgtPkkwIWOgEqIhEvdjEvYXV0aC9yZWdpc3RlchJPCgVMb2dpbhIULmRveC52MS5Mb2dpblJlcXVlc3QaFS5kb3gudjEuTG9naW5SZXNwb25zZSIZgtPkkwITOgEqIg4vdjEvYXV0aC9sb2dpbkI2WjRnaXRodWIuY29tL2xpbi1zbm93L2RveC9hcHBzL3NlcnZlci9nZW4vZG94L3YxO2RveHYxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * @generated from message dox.v1.ServerInfoRequest
 */
export type ServerInfoRequest = Message<"dox.v1.ServerInfoRequest"> & {
};

/**
 * Describes the message dox.v1.ServerInfoRequest.
 * Use `create(ServerInfoRequestSchema)` to create a new message.
 */
export const ServerInfoRequestSchema: GenMessage<ServerInfoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 0);

/**
 * @generated from message dox.v1.ServerInfoResponse
 */
export type ServerInfoResponse = Message<"dox.v1.ServerInfoResponse"> & {
  /**
   * True once the server has at least one registered user. When false, the
   * next Register call promotes the caller to owner regardless of invite/
   * registration policy.
   *
   * @generated from field: bool has_users = 1;
   */
  hasUsers: boolean;

  /**
   * Mirrors the registration_open server setting. When true, Register works
   * without an invite code (only meaningful once has_users is true).
   *
   * @generated from field: bool registration_open = 2;
   */
  registrationOpen: boolean;

  /**
   * Server build identity, surfaced unauthenticated so a CLI can warn on
   * CLI/server version skew before login.
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * Short commit sha for the running server build. May carry a "-dirty"
   * suffix for local builds.
   *
   * @generated from field: string commit = 4;
   */
  commit: string;

  /**
   * Owner-set display name. Empty until configured.
   *
   * @generated from field: string server_name = 5;
   */
  serverName: string;

  /**
   * Owner-set one-liner description. Empty until configured.
   *
   * @generated from field: string server_description = 6;
   */
  serverDescription: string;

  /**
   * Display name of the server owner. Empty until first Register completes.
   *
   * @generated from field: string owner_name = 7;
   */
  ownerName: string;
};

/**
 * Describes the message dox.v1.ServerInfoResponse.
 * Use `create(ServerInfoResponseSchema)` to create a new message.
 */
export const ServerInfoResponseSchema: GenMessage<ServerInfoResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 1);

/**
 * @generated from message dox.v1.RegisterRequest
 */
export type RegisterRequest = Message<"dox.v1.RegisterRequest"> & {
  /**
   * Display name for the new user. Must be unique across the server.
   *
   * @generated from field: string user_name = 1;
   */
  userName: string;

  /**
   * Plaintext password. Server hashes with argon2id. Min 8 chars.
   *
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * Required when registration is closed and the users table is non-empty.
   *
   * @generated from field: optional string invite_code = 3;
   */
  inviteCode?: string | undefined;

  /**
   * First-user only: optional server identity fields. Ignored on subsequent
   * Register calls — owners change them later via UpdateServerSettings.
   *
   * @generated from field: optional string server_name = 4;
   */
  serverName?: string | undefined;

  /**
   * @generated from field: optional string server_description = 5;
   */
  serverDescription?: string | undefined;
};

/**
 * Describes the message dox.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 2);

/**
 * @generated from message dox.v1.RegisterResponse
 */
export type RegisterResponse = Message<"dox.v1.RegisterResponse"> & {
  /**
   * JWT (HS256). Caller stores it and presents as Authorization: Bearer.
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 3;
   */
  userName: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;
};

/**
 * Describes the message dox.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 3);

/**
 * @generated from message dox.v1.LoginRequest
 */
export type LoginRequest = Message<"dox.v1.LoginRequest"> & {
  /**
   * @generated from field: string user_name = 1;
   */
  userName: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message dox.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 4);

/**
 * @generated from message dox.v1.LoginResponse
 */
export type LoginResponse = Message<"dox.v1.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string user_name = 3;
   */
  userName: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;
};

/**
 * Describes the message dox.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_auth, 5);

/**
 * AuthService hosts the public (unauthenticated) RPCs:
 *   - ServerInfo lets a client probe a server before logging in so the
 *     onboarding UI can pick the right branch (first-user / existing-user
 *     login / register-with-invite) and surface the server's identity.
 *   - Register creates a user. The first-ever Register on an empty server
 *     makes the caller the owner and may set the server's display
 *     name/description inline. Subsequent Registers require either a valid
 *     invite code or registration_open=true.
 *   - Login authenticates an existing user with username + password and
 *     returns a JWT.
 *
 * @generated from service dox.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc dox.v1.AuthService.ServerInfo
   */
  serverInfo: {
    methodKind: "unary";
    input: typeof ServerInfoRequestSchema;
    output: typeof ServerInfoResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_auth, 0);

