// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/event.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/event.proto.
 */
export const file_dox_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChJkb3gvdjEvZXZlbnQucHJvdG8SBmRveC52MSLaAQoFRXZlbnQSCgoCaWQYASABKAkSDAoEdmVyYhgCIAEoCRIQCghhY3Rvcl9pZBgDIAEoCRISCgphY3Rvcl9uYW1lGAQgASgJEhIKCnByb2plY3RfaWQYBSABKAkSFAoMcHJvamVjdF9uYW1lGAYgASgJEhUKDXByb2plY3RfY29sb3IYByABKAkSEwoLdGFyZ2V0X3R5cGUYCCABKAkSEQoJdGFyZ2V0X2lkGAkgASgJEhQKDHRhcmdldF9sYWJlbBgKIAEoCRISCgpjcmVhdGVkX2F0GAsgASgDIiIKEUxpc3RFdmVudHNSZXF1ZXN0Eg0KBWxpbWl0GAEgASgNIjMKEkxpc3RFdmVudHNSZXNwb25zZRIdCgZldmVudHMYASADKAsyDS5kb3gudjEuRXZlbnQyZwoMRXZlbnRTZXJ2aWNlElcKCkxpc3RFdmVudHMSGS5kb3gudjEuTGlzdEV2ZW50c1JlcXVlc3QaGi5kb3gudjEuTGlzdEV2ZW50c1Jlc3BvbnNlIhKC0+STAgwSCi92MS9ldmVudHNCNlo0Z2l0aHViLmNvbS9saW4tc25vdy9kb3gvYXBwcy9zZXJ2ZXIvZ2VuL2RveC92MTtkb3h2MWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * Event is a single activity row visible to the caller. Emitted by the server
 * at mutation points (todo create / complete, project member join) and read by
 * clients via ListEvents. Read-only — no mutation RPCs.
 *
 * @generated from message dox.v1.Event
 */
export type Event = Message<"dox.v1.Event"> & {
  /**
   * ULID, primary key.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Verb describing what happened. v1 values:
   *   "todo_created" | "todo_completed" | "member_joined"
   *
   * @generated from field: string verb = 2;
   */
  verb: string;

  /**
   * The user who triggered the event.
   *
   * @generated from field: string actor_id = 3;
   */
  actorId: string;

  /**
   * Snapshot of the actor's name at read time (joined server-side).
   *
   * @generated from field: string actor_name = 4;
   */
  actorName: string;

  /**
   * The project the event happened in. Always set in v1.
   *
   * @generated from field: string project_id = 5;
   */
  projectId: string;

  /**
   * Snapshot of the project's name at read time.
   *
   * @generated from field: string project_name = 6;
   */
  projectName: string;

  /**
   * Snapshot of the project's color swatch.
   *
   * @generated from field: string project_color = 7;
   */
  projectColor: string;

  /**
   * Either "todo" or "project" — tells clients what target_id refers to.
   *
   * @generated from field: string target_type = 8;
   */
  targetType: string;

  /**
   * ULID of the underlying todo or project.
   *
   * @generated from field: string target_id = 9;
   */
  targetId: string;

  /**
   * Snapshot of the target's display label (todo title / project name) taken
   * at write time, so renamed/deleted targets still render sensibly.
   *
   * @generated from field: string target_label = 10;
   */
  targetLabel: string;

  /**
   * Event time, UTC unix milliseconds.
   *
   * @generated from field: int64 created_at = 11;
   */
  createdAt: bigint;
};

/**
 * Describes the message dox.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_dox_v1_event, 0);

/**
 * @generated from message dox.v1.ListEventsRequest
 */
export type ListEventsRequest = Message<"dox.v1.ListEventsRequest"> & {
  /**
   * Max events to return. Server clamps to [1, 50]; 0 falls back to 20.
   *
   * @generated from field: uint32 limit = 1;
   */
  limit: number;
};

/**
 * Describes the message dox.v1.ListEventsRequest.
 * Use `create(ListEventsRequestSchema)` to create a new message.
 */
export const ListEventsRequestSchema: GenMessage<ListEventsRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_event, 1);

/**
 * @generated from message dox.v1.ListEventsResponse
 */
export type ListEventsResponse = Message<"dox.v1.ListEventsResponse"> & {
  /**
   * @generated from field: repeated dox.v1.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message dox.v1.ListEventsResponse.
 * Use `create(ListEventsResponseSchema)` to create a new message.
 */
export const ListEventsResponseSchema: GenMessage<ListEventsResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_event, 2);

/**
 * EventService surfaces the activity feed for the authenticated user.
 *
 * @generated from service dox.v1.EventService
 */
export const EventService: GenService<{
  /**
   * ListEvents returns recent events from the caller's visible projects, newest
   * first. Empty response when the caller has no project memberships.
   *
   * @generated from rpc dox.v1.EventService.ListEvents
   */
  listEvents: {
    methodKind: "unary";
    input: typeof ListEventsRequestSchema;
    output: typeof ListEventsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_event, 0);

