// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/invite.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/invite.proto.
 */
export const file_dox_v1_invite: GenFile = /*@__PURE__*/
  fileDesc("ChNkb3gvdjEvaW52aXRlLnByb3RvEgZkb3gudjEicwoGSW52aXRlEgwKBGNvZGUYASABKAkSEQoJaXNzdWVkX2J5GAIgASgJEhIKCnByb2plY3RfaWQYAyABKAkSDAoEcm9sZRgEIAEoCRISCgpjcmVhdGVkX2F0GAUgASgDEhIKCmV4cGlyZXNfYXQYBiABKAMiaQoTQ3JlYXRlSW52aXRlUmVxdWVzdBIXCgpwcm9qZWN0X2lkGAEgASgJSACIAQESEQoEcm9sZRgCIAEoCUgBiAEBEg4KBnR0bF9tcxgDIAEoA0INCgtfcHJvamVjdF9pZEIHCgVfcm9sZSIjChNBY2NlcHRJbnZpdGVSZXF1ZXN0EgwKBGNvZGUYASABKAkiOAoUQWNjZXB0SW52aXRlUmVzcG9uc2USEgoKcHJvamVjdF9pZBgBIAEoCRIMCgRyb2xlGAIgASgJMs4BCg1JbnZpdGVTZXJ2aWNlElMKDENyZWF0ZUludml0ZRIbLmRveC52MS5DcmVhdGVJbnZpdGVSZXF1ZXN0Gg4uZG94LnYxLkludml0ZSIWgtPkkwIQOgEqIgsvdjEvaW52aXRlcxJoCgxBY2NlcHRJbnZpdGUSGy5kb3gudjEuQWNjZXB0SW52aXRlUmVxdWVzdBocLmRveC52MS5BY2NlcHRJbnZpdGVSZXNwb25zZSIdgtPkkwIXOgEqIhIvdjEvaW52aXRlcy9hY2NlcHRCNlo0Z2l0aHViLmNvbS9saW4tc25vdy9kb3gvYXBwcy9zZXJ2ZXIvZ2VuL2RveC92MTtkb3h2MWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * @generated from message dox.v1.Invite
 */
export type Invite = Message<"dox.v1.Invite"> & {
  /**
   * Plaintext code. Returned only when the invite is created; stored hashed.
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string issued_by = 2;
   */
  issuedBy: string;

  /**
   * Empty for server-level invites.
   *
   * @generated from field: string project_id = 3;
   */
  projectId: string;

  /**
   * Empty for server-level invites; otherwise "editor" or "viewer".
   *
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 expires_at = 6;
   */
  expiresAt: bigint;
};

/**
 * Describes the message dox.v1.Invite.
 * Use `create(InviteSchema)` to create a new message.
 */
export const InviteSchema: GenMessage<Invite> = /*@__PURE__*/
  messageDesc(file_dox_v1_invite, 0);

/**
 * @generated from message dox.v1.CreateInviteRequest
 */
export type CreateInviteRequest = Message<"dox.v1.CreateInviteRequest"> & {
  /**
   * Unset = server-level invite (owner only). Set = project invite.
   *
   * @generated from field: optional string project_id = 1;
   */
  projectId?: string | undefined;

  /**
   * Required iff project_id is set. "editor" or "viewer".
   *
   * @generated from field: optional string role = 2;
   */
  role?: string | undefined;

  /**
   * Code lifetime in milliseconds. 0 → 24h.
   *
   * @generated from field: int64 ttl_ms = 3;
   */
  ttlMs: bigint;
};

/**
 * Describes the message dox.v1.CreateInviteRequest.
 * Use `create(CreateInviteRequestSchema)` to create a new message.
 */
export const CreateInviteRequestSchema: GenMessage<CreateInviteRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_invite, 1);

/**
 * @generated from message dox.v1.AcceptInviteRequest
 */
export type AcceptInviteRequest = Message<"dox.v1.AcceptInviteRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message dox.v1.AcceptInviteRequest.
 * Use `create(AcceptInviteRequestSchema)` to create a new message.
 */
export const AcceptInviteRequestSchema: GenMessage<AcceptInviteRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_invite, 2);

/**
 * @generated from message dox.v1.AcceptInviteResponse
 */
export type AcceptInviteResponse = Message<"dox.v1.AcceptInviteResponse"> & {
  /**
   * The project the caller joined; empty if the code was a server invite,
   * which AcceptInvite rejects (server invites are only redeemable via Register).
   *
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string role = 2;
   */
  role: string;
};

/**
 * Describes the message dox.v1.AcceptInviteResponse.
 * Use `create(AcceptInviteResponseSchema)` to create a new message.
 */
export const AcceptInviteResponseSchema: GenMessage<AcceptInviteResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_invite, 3);

/**
 * InviteService issues and accepts invitation codes. A server invite
 * (project_id unset) is owner-only and brings a new user onto the server via
 * AuthService.Register. A project invite (project_id set) is project-owner-only
 * and either brings a new user onto the server + into the project (via
 * Register) or just adds an existing user to the project (via AcceptInvite).
 *
 * @generated from service dox.v1.InviteService
 */
export const InviteService: GenService<{
  /**
   * @generated from rpc dox.v1.InviteService.CreateInvite
   */
  createInvite: {
    methodKind: "unary";
    input: typeof CreateInviteRequestSchema;
    output: typeof InviteSchema;
  },
  /**
   * @generated from rpc dox.v1.InviteService.AcceptInvite
   */
  acceptInvite: {
    methodKind: "unary";
    input: typeof AcceptInviteRequestSchema;
    output: typeof AcceptInviteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_invite, 0);

