// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/todo.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/todo.proto.
 */
export const file_dox_v1_todo: GenFile = /*@__PURE__*/
  fileDesc("ChFkb3gvdjEvdG9kby5wcm90bxIGZG94LnYxIpMBCgRUb2RvEgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEgwKBGRvbmUYAyABKAgSEgoKY3JlYXRlZF9hdBgEIAEoAxISCgp1cGRhdGVkX2F0GAUgASgDEhcKCnByb2plY3RfaWQYBiABKAlIAIgBARISCgpjcmVhdGVkX2J5GAcgASgJQg0KC19wcm9qZWN0X2lkIjoKEExpc3RUb2Rvc1JlcXVlc3QSFwoKcHJvamVjdF9pZBgBIAEoCUgAiAEBQg0KC19wcm9qZWN0X2lkIjAKEUxpc3RUb2Rvc1Jlc3BvbnNlEhsKBXRvZG9zGAEgAygLMgwuZG94LnYxLlRvZG8iHAoOR2V0VG9kb1JlcXVlc3QSCgoCaWQYASABKAkiSgoRQ3JlYXRlVG9kb1JlcXVlc3QSDQoFdGl0bGUYASABKAkSFwoKcHJvamVjdF9pZBgCIAEoCUgAiAEBQg0KC19wcm9qZWN0X2lkIlkKEVVwZGF0ZVRvZG9SZXF1ZXN0EgoKAmlkGAEgASgJEhIKBXRpdGxlGAIgASgJSACIAQESEQoEZG9uZRgDIAEoCEgBiAEBQggKBl90aXRsZUIHCgVfZG9uZSIfChFEZWxldGVUb2RvUmVxdWVzdBIKCgJpZBgBIAEoCSIUChJEZWxldGVUb2RvUmVzcG9uc2UypwMKC1RvZG9TZXJ2aWNlElMKCUxpc3RUb2RvcxIYLmRveC52MS5MaXN0VG9kb3NSZXF1ZXN0GhkuZG94LnYxLkxpc3RUb2Rvc1Jlc3BvbnNlIhGC0+STAgsSCS92MS90b2RvcxJHCgdHZXRUb2RvEhYuZG94LnYxLkdldFRvZG9SZXF1ZXN0GgwuZG94LnYxLlRvZG8iFoLT5JMCEBIOL3YxL3RvZG9zL3tpZH0SSwoKQ3JlYXRlVG9kbxIZLmRveC52MS5DcmVhdGVUb2RvUmVxdWVzdBoMLmRveC52MS5Ub2RvIhSC0+STAg46ASoiCS92MS90b2RvcxJQCgpVcGRhdGVUb2RvEhkuZG94LnYxLlVwZGF0ZVRvZG9SZXF1ZXN0GgwuZG94LnYxLlRvZG8iGYLT5JMCEzoBKjIOL3YxL3RvZG9zL3tpZH0SWwoKRGVsZXRlVG9kbxIZLmRveC52MS5EZWxldGVUb2RvUmVxdWVzdBoaLmRveC52MS5EZWxldGVUb2RvUmVzcG9uc2UiFoLT5JMCECoOL3YxL3RvZG9zL3tpZH1CNlo0Z2l0aHViLmNvbS9saW4tc25vdy9kb3gvYXBwcy9zZXJ2ZXIvZ2VuL2RveC92MTtkb3h2MWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * Todo is a single todo item, owned by a user and optionally scoped to a project.
 *
 * @generated from message dox.v1.Todo
 */
export type Todo = Message<"dox.v1.Todo"> & {
  /**
   * Server-generated ULID, primary key.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Whether the todo is marked done.
   *
   * @generated from field: bool done = 3;
   */
  done: boolean;

  /**
   * Creation time, UTC unix milliseconds.
   *
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  /**
   * Last update time, UTC unix milliseconds.
   *
   * @generated from field: int64 updated_at = 5;
   */
  updatedAt: bigint;

  /**
   * Project the todo belongs to. Unset = Inbox (private to created_by).
   *
   * @generated from field: optional string project_id = 6;
   */
  projectId?: string | undefined;

  /**
   * User who created the todo.
   *
   * @generated from field: string created_by = 7;
   */
  createdBy: string;
};

/**
 * Describes the message dox.v1.Todo.
 * Use `create(TodoSchema)` to create a new message.
 */
export const TodoSchema: GenMessage<Todo> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 0);

/**
 * @generated from message dox.v1.ListTodosRequest
 */
export type ListTodosRequest = Message<"dox.v1.ListTodosRequest"> & {
  /**
   * Filter the listing. Unset = everything visible to caller. "inbox" = Inbox
   * only. A project id = that project only (caller must be owner or member).
   *
   * @generated from field: optional string project_id = 1;
   */
  projectId?: string | undefined;
};

/**
 * Describes the message dox.v1.ListTodosRequest.
 * Use `create(ListTodosRequestSchema)` to create a new message.
 */
export const ListTodosRequestSchema: GenMessage<ListTodosRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 1);

/**
 * @generated from message dox.v1.ListTodosResponse
 */
export type ListTodosResponse = Message<"dox.v1.ListTodosResponse"> & {
  /**
   * @generated from field: repeated dox.v1.Todo todos = 1;
   */
  todos: Todo[];
};

/**
 * Describes the message dox.v1.ListTodosResponse.
 * Use `create(ListTodosResponseSchema)` to create a new message.
 */
export const ListTodosResponseSchema: GenMessage<ListTodosResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 2);

/**
 * @generated from message dox.v1.GetTodoRequest
 */
export type GetTodoRequest = Message<"dox.v1.GetTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dox.v1.GetTodoRequest.
 * Use `create(GetTodoRequestSchema)` to create a new message.
 */
export const GetTodoRequestSchema: GenMessage<GetTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 3);

/**
 * @generated from message dox.v1.CreateTodoRequest
 */
export type CreateTodoRequest = Message<"dox.v1.CreateTodoRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Unset = create in Inbox (private to caller).
   *
   * @generated from field: optional string project_id = 2;
   */
  projectId?: string | undefined;
};

/**
 * Describes the message dox.v1.CreateTodoRequest.
 * Use `create(CreateTodoRequestSchema)` to create a new message.
 */
export const CreateTodoRequestSchema: GenMessage<CreateTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 4);

/**
 * @generated from message dox.v1.UpdateTodoRequest
 */
export type UpdateTodoRequest = Message<"dox.v1.UpdateTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string | undefined;

  /**
   * @generated from field: optional bool done = 3;
   */
  done?: boolean | undefined;
};

/**
 * Describes the message dox.v1.UpdateTodoRequest.
 * Use `create(UpdateTodoRequestSchema)` to create a new message.
 */
export const UpdateTodoRequestSchema: GenMessage<UpdateTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 5);

/**
 * @generated from message dox.v1.DeleteTodoRequest
 */
export type DeleteTodoRequest = Message<"dox.v1.DeleteTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dox.v1.DeleteTodoRequest.
 * Use `create(DeleteTodoRequestSchema)` to create a new message.
 */
export const DeleteTodoRequestSchema: GenMessage<DeleteTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 6);

/**
 * @generated from message dox.v1.DeleteTodoResponse
 */
export type DeleteTodoResponse = Message<"dox.v1.DeleteTodoResponse"> & {
};

/**
 * Describes the message dox.v1.DeleteTodoResponse.
 * Use `create(DeleteTodoResponseSchema)` to create a new message.
 */
export const DeleteTodoResponseSchema: GenMessage<DeleteTodoResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 7);

/**
 * TodoService manages todos for the authenticated user.
 *
 * @generated from service dox.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * ListTodos returns todos visible to the caller. With no project_id filter
   * it returns the caller's Inbox plus every project they own or are a member
   * of. project_id == "inbox" filters to Inbox only.
   *
   * @generated from rpc dox.v1.TodoService.ListTodos
   */
  listTodos: {
    methodKind: "unary";
    input: typeof ListTodosRequestSchema;
    output: typeof ListTodosResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.GetTodo
   */
  getTodo: {
    methodKind: "unary";
    input: typeof GetTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.CreateTodo
   */
  createTodo: {
    methodKind: "unary";
    input: typeof CreateTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.UpdateTodo
   */
  updateTodo: {
    methodKind: "unary";
    input: typeof UpdateTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.DeleteTodo
   */
  deleteTodo: {
    methodKind: "unary";
    input: typeof DeleteTodoRequestSchema;
    output: typeof DeleteTodoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_todo, 0);

