// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/todo.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/todo.proto.
 */
export const file_dox_v1_todo: GenFile = /*@__PURE__*/
  fileDesc("ChFkb3gvdjEvdG9kby5wcm90bxIGZG94LnYxIr0BCgRUb2RvEgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEgwKBGRvbmUYAyABKAgSEgoKY3JlYXRlZF9hdBgEIAEoAxISCgp1cGRhdGVkX2F0GAUgASgDEhcKCnByb2plY3RfaWQYBiABKAlIAIgBARISCgpjcmVhdGVkX2J5GAcgASgJEhgKC2Rlc2NyaXB0aW9uGAggASgJSAGIAQFCDQoLX3Byb2plY3RfaWRCDgoMX2Rlc2NyaXB0aW9uIjoKEExpc3RUb2Rvc1JlcXVlc3QSFwoKcHJvamVjdF9pZBgBIAEoCUgAiAEBQg0KC19wcm9qZWN0X2lkIjAKEUxpc3RUb2Rvc1Jlc3BvbnNlEhsKBXRvZG9zGAEgAygLMgwuZG94LnYxLlRvZG8iHAoOR2V0VG9kb1JlcXVlc3QSCgoCaWQYASABKAkidAoRQ3JlYXRlVG9kb1JlcXVlc3QSDQoFdGl0bGUYASABKAkSFwoKcHJvamVjdF9pZBgCIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAMgASgJSAGIAQFCDQoLX3Byb2plY3RfaWRCDgoMX2Rlc2NyaXB0aW9uIoMBChFVcGRhdGVUb2RvUmVxdWVzdBIKCgJpZBgBIAEoCRISCgV0aXRsZRgCIAEoCUgAiAEBEhEKBGRvbmUYAyABKAhIAYgBARIYCgtkZXNjcmlwdGlvbhgEIAEoCUgCiAEBQggKBl90aXRsZUIHCgVfZG9uZUIOCgxfZGVzY3JpcHRpb24iHwoRRGVsZXRlVG9kb1JlcXVlc3QSCgoCaWQYASABKAkiFAoSRGVsZXRlVG9kb1Jlc3BvbnNlMqcDCgtUb2RvU2VydmljZRJTCglMaXN0VG9kb3MSGC5kb3gudjEuTGlzdFRvZG9zUmVxdWVzdBoZLmRveC52MS5MaXN0VG9kb3NSZXNwb25zZSIRgtPkkwILEgkvdjEvdG9kb3MSRwoHR2V0VG9kbxIWLmRveC52MS5HZXRUb2RvUmVxdWVzdBoMLmRveC52MS5Ub2RvIhaC0+STAhASDi92MS90b2Rvcy97aWR9EksKCkNyZWF0ZVRvZG8SGS5kb3gudjEuQ3JlYXRlVG9kb1JlcXVlc3QaDC5kb3gudjEuVG9kbyIUgtPkkwIOOgEqIgkvdjEvdG9kb3MSUAoKVXBkYXRlVG9kbxIZLmRveC52MS5VcGRhdGVUb2RvUmVxdWVzdBoMLmRveC52MS5Ub2RvIhmC0+STAhM6ASoyDi92MS90b2Rvcy97aWR9ElsKCkRlbGV0ZVRvZG8SGS5kb3gudjEuRGVsZXRlVG9kb1JlcXVlc3QaGi5kb3gudjEuRGVsZXRlVG9kb1Jlc3BvbnNlIhaC0+STAhAqDi92MS90b2Rvcy97aWR9QjZaNGdpdGh1Yi5jb20vbGluLXNub3cvZG94L2FwcHMvc2VydmVyL2dlbi9kb3gvdjE7ZG94djFiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Todo is a single todo item, owned by a user and optionally scoped to a project.
 *
 * @generated from message dox.v1.Todo
 */
export type Todo = Message<"dox.v1.Todo"> & {
  /**
   * Server-generated ULID, primary key.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Whether the todo is marked done.
   *
   * @generated from field: bool done = 3;
   */
  done: boolean;

  /**
   * Creation time, UTC unix milliseconds.
   *
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  /**
   * Last update time, UTC unix milliseconds.
   *
   * @generated from field: int64 updated_at = 5;
   */
  updatedAt: bigint;

  /**
   * Project the todo belongs to. Unset = Inbox (private to created_by).
   *
   * @generated from field: optional string project_id = 6;
   */
  projectId?: string | undefined;

  /**
   * User who created the todo.
   *
   * @generated from field: string created_by = 7;
   */
  createdBy: string;

  /**
   * Optional long-form body, rendered as markdown by clients. Populated only
   * by GetTodo / CreateTodo / UpdateTodo — ListTodos omits it to keep list
   * payloads small.
   *
   * @generated from field: optional string description = 8;
   */
  description?: string | undefined;
};

/**
 * Describes the message dox.v1.Todo.
 * Use `create(TodoSchema)` to create a new message.
 */
export const TodoSchema: GenMessage<Todo> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 0);

/**
 * @generated from message dox.v1.ListTodosRequest
 */
export type ListTodosRequest = Message<"dox.v1.ListTodosRequest"> & {
  /**
   * Filter the listing. Unset = everything visible to caller. "inbox" = Inbox
   * only. A project id = that project only (caller must be owner or member).
   *
   * @generated from field: optional string project_id = 1;
   */
  projectId?: string | undefined;
};

/**
 * Describes the message dox.v1.ListTodosRequest.
 * Use `create(ListTodosRequestSchema)` to create a new message.
 */
export const ListTodosRequestSchema: GenMessage<ListTodosRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 1);

/**
 * @generated from message dox.v1.ListTodosResponse
 */
export type ListTodosResponse = Message<"dox.v1.ListTodosResponse"> & {
  /**
   * @generated from field: repeated dox.v1.Todo todos = 1;
   */
  todos: Todo[];
};

/**
 * Describes the message dox.v1.ListTodosResponse.
 * Use `create(ListTodosResponseSchema)` to create a new message.
 */
export const ListTodosResponseSchema: GenMessage<ListTodosResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 2);

/**
 * @generated from message dox.v1.GetTodoRequest
 */
export type GetTodoRequest = Message<"dox.v1.GetTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dox.v1.GetTodoRequest.
 * Use `create(GetTodoRequestSchema)` to create a new message.
 */
export const GetTodoRequestSchema: GenMessage<GetTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 3);

/**
 * @generated from message dox.v1.CreateTodoRequest
 */
export type CreateTodoRequest = Message<"dox.v1.CreateTodoRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Unset = create in Inbox (private to caller).
   *
   * @generated from field: optional string project_id = 2;
   */
  projectId?: string | undefined;

  /**
   * Optional markdown description. Empty string is treated as unset.
   *
   * @generated from field: optional string description = 3;
   */
  description?: string | undefined;
};

/**
 * Describes the message dox.v1.CreateTodoRequest.
 * Use `create(CreateTodoRequestSchema)` to create a new message.
 */
export const CreateTodoRequestSchema: GenMessage<CreateTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 4);

/**
 * @generated from message dox.v1.UpdateTodoRequest
 */
export type UpdateTodoRequest = Message<"dox.v1.UpdateTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string | undefined;

  /**
   * @generated from field: optional bool done = 3;
   */
  done?: boolean | undefined;

  /**
   * Patch the markdown description. Empty string clears it.
   *
   * @generated from field: optional string description = 4;
   */
  description?: string | undefined;
};

/**
 * Describes the message dox.v1.UpdateTodoRequest.
 * Use `create(UpdateTodoRequestSchema)` to create a new message.
 */
export const UpdateTodoRequestSchema: GenMessage<UpdateTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 5);

/**
 * @generated from message dox.v1.DeleteTodoRequest
 */
export type DeleteTodoRequest = Message<"dox.v1.DeleteTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message dox.v1.DeleteTodoRequest.
 * Use `create(DeleteTodoRequestSchema)` to create a new message.
 */
export const DeleteTodoRequestSchema: GenMessage<DeleteTodoRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 6);

/**
 * @generated from message dox.v1.DeleteTodoResponse
 */
export type DeleteTodoResponse = Message<"dox.v1.DeleteTodoResponse"> & {
};

/**
 * Describes the message dox.v1.DeleteTodoResponse.
 * Use `create(DeleteTodoResponseSchema)` to create a new message.
 */
export const DeleteTodoResponseSchema: GenMessage<DeleteTodoResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 7);

/**
 * TodoService manages todos for the authenticated user.
 *
 * @generated from service dox.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * ListTodos returns todos visible to the caller. With no project_id filter
   * it returns the caller's Inbox plus every project they own or are a member
   * of. project_id == "inbox" filters to Inbox only.
   *
   * @generated from rpc dox.v1.TodoService.ListTodos
   */
  listTodos: {
    methodKind: "unary";
    input: typeof ListTodosRequestSchema;
    output: typeof ListTodosResponseSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.GetTodo
   */
  getTodo: {
    methodKind: "unary";
    input: typeof GetTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.CreateTodo
   */
  createTodo: {
    methodKind: "unary";
    input: typeof CreateTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.UpdateTodo
   */
  updateTodo: {
    methodKind: "unary";
    input: typeof UpdateTodoRequestSchema;
    output: typeof TodoSchema;
  },
  /**
   * @generated from rpc dox.v1.TodoService.DeleteTodo
   */
  deleteTodo: {
    methodKind: "unary";
    input: typeof DeleteTodoRequestSchema;
    output: typeof DeleteTodoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_todo, 0);

