// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dox/v1/todo.proto (package dox.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dox/v1/todo.proto.
 */
export const file_dox_v1_todo: GenFile = /*@__PURE__*/
  fileDesc("ChFkb3gvdjEvdG9kby5wcm90bxIGZG94LnYxIlcKBFRvZG8SCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSDAoEZG9uZRgDIAEoCBISCgpjcmVhdGVkX2F0GAQgASgDEhIKCnVwZGF0ZWRfYXQYBSABKAMiEgoQTGlzdFRvZG9zUmVxdWVzdCIwChFMaXN0VG9kb3NSZXNwb25zZRIbCgV0b2RvcxgBIAMoCzIMLmRveC52MS5Ub2RvMmIKC1RvZG9TZXJ2aWNlElMKCUxpc3RUb2RvcxIYLmRveC52MS5MaXN0VG9kb3NSZXF1ZXN0GhkuZG94LnYxLkxpc3RUb2Rvc1Jlc3BvbnNlIhGC0+STAgsSCS92MS90b2Rvc0I2WjRnaXRodWIuY29tL2xpbi1zbm93L2RveC9hcHBzL3NlcnZlci9nZW4vZG94L3YxO2RveHYxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * Todo is a single todo item.
 *
 * @generated from message dox.v1.Todo
 */
export type Todo = Message<"dox.v1.Todo"> & {
  /**
   * Server-generated ULID, primary key.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Whether the todo is marked done.
   *
   * @generated from field: bool done = 3;
   */
  done: boolean;

  /**
   * Creation time, UTC unix milliseconds.
   *
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  /**
   * Last update time, UTC unix milliseconds.
   *
   * @generated from field: int64 updated_at = 5;
   */
  updatedAt: bigint;
};

/**
 * Describes the message dox.v1.Todo.
 * Use `create(TodoSchema)` to create a new message.
 */
export const TodoSchema: GenMessage<Todo> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 0);

/**
 * @generated from message dox.v1.ListTodosRequest
 */
export type ListTodosRequest = Message<"dox.v1.ListTodosRequest"> & {
};

/**
 * Describes the message dox.v1.ListTodosRequest.
 * Use `create(ListTodosRequestSchema)` to create a new message.
 */
export const ListTodosRequestSchema: GenMessage<ListTodosRequest> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 1);

/**
 * @generated from message dox.v1.ListTodosResponse
 */
export type ListTodosResponse = Message<"dox.v1.ListTodosResponse"> & {
  /**
   * @generated from field: repeated dox.v1.Todo todos = 1;
   */
  todos: Todo[];
};

/**
 * Describes the message dox.v1.ListTodosResponse.
 * Use `create(ListTodosResponseSchema)` to create a new message.
 */
export const ListTodosResponseSchema: GenMessage<ListTodosResponse> = /*@__PURE__*/
  messageDesc(file_dox_v1_todo, 2);

/**
 * TodoService manages todos for the authenticated device.
 *
 * @generated from service dox.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * ListTodos returns all todos.
   *
   * @generated from rpc dox.v1.TodoService.ListTodos
   */
  listTodos: {
    methodKind: "unary";
    input: typeof ListTodosRequestSchema;
    output: typeof ListTodosResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dox_v1_todo, 0);

