// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"
)

const consumePairingCode = `-- name: ConsumePairingCode :one
UPDATE pairing_codes
SET used = 1
WHERE code = ?1
  AND used = 0
  AND expires_at >= ?2
RETURNING name
`

type ConsumePairingCodeParams struct {
	Code string
	Now  int64
}

// Atomically marks the code as used and returns its name if it was still valid.
// Returns no row if the code is missing, expired, or already consumed.
func (q *Queries) ConsumePairingCode(ctx context.Context, arg ConsumePairingCodeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, consumePairingCode, arg.Code, arg.Now)
	var name string
	err := row.Scan(&name)
	return name, err
}

const createDeviceToken = `-- name: CreateDeviceToken :exec
INSERT INTO device_tokens (id, name, token_hash, created_at, last_seen_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeviceTokenParams struct {
	ID         string
	Name       string
	TokenHash  string
	CreatedAt  int64
	LastSeenAt int64
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, createDeviceToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	return err
}

const createPairingCode = `-- name: CreatePairingCode :exec
INSERT INTO pairing_codes (code, name, expires_at, used)
VALUES (?, ?, ?, 0)
`

type CreatePairingCodeParams struct {
	Code      string
	Name      string
	ExpiresAt int64
}

func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPairingCode, arg.Code, arg.Name, arg.ExpiresAt)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :execrows
DELETE FROM device_tokens
WHERE id = ?
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredPairingCodes = `-- name: DeleteExpiredPairingCodes :execrows
DELETE FROM pairing_codes
WHERE expires_at < ? OR used = 1
`

func (q *Queries) DeleteExpiredPairingCodes(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredPairingCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findDeviceByTokenHash = `-- name: FindDeviceByTokenHash :one
SELECT id, name, token_hash, created_at, last_seen_at
FROM device_tokens
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) FindDeviceByTokenHash(ctx context.Context, tokenHash string) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, findDeviceByTokenHash, tokenHash)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listDeviceTokens = `-- name: ListDeviceTokens :many
SELECT id, name, token_hash, created_at, last_seen_at
FROM device_tokens
ORDER BY created_at DESC
`

func (q *Queries) ListDeviceTokens(ctx context.Context) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE device_tokens
SET last_seen_at = ?
WHERE id = ?
`

type TouchDeviceLastSeenParams struct {
	LastSeenAt int64
	ID         string
}

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, arg TouchDeviceLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, touchDeviceLastSeen, arg.LastSeenAt, arg.ID)
	return err
}
