// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package queries

import (
	"context"
	"database/sql"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, verb, actor_id, project_id, target_type, target_id, target_label, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID          string
	Verb        string
	ActorID     string
	ProjectID   string
	TargetType  string
	TargetID    string
	TargetLabel string
	CreatedAt   int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Verb,
		arg.ActorID,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.TargetLabel,
		arg.CreatedAt,
	)
	return err
}

const listEventsForUser = `-- name: ListEventsForUser :many
SELECT
    e.id,
    e.verb,
    e.actor_id,
    u.name      AS actor_name,
    e.project_id,
    p.name      AS project_name,
    p.color     AS project_color,
    e.target_type,
    e.target_id,
    e.target_label,
    e.created_at
FROM events e
JOIN users    u ON u.id = e.actor_id
JOIN projects p ON p.id = e.project_id
WHERE p.owner_id = ?1
   OR EXISTS (
        SELECT 1 FROM project_members m
        WHERE m.project_id = e.project_id AND m.user_id = ?1
   )
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?2
`

type ListEventsForUserParams struct {
	UserID string
	LimitN int64
}

type ListEventsForUserRow struct {
	ID           string
	Verb         string
	ActorID      string
	ActorName    string
	ProjectID    string
	ProjectName  string
	ProjectColor sql.NullString
	TargetType   string
	TargetID     string
	TargetLabel  string
	CreatedAt    int64
}

// Recent events across the caller's visible projects (owned + member-of).
// Joins users + projects so the handler returns a fully populated response
// without follow-up queries. Visibility filter mirrors ListProjectsVisibleTo /
// ListTodosForUser so authz semantics stay consistent across resources.
// ULIDs are lexicographically time-ordered, so the id tiebreaker keeps the
// feed stable when two events land in the same millisecond (common when a
// mutation handler emits + the caller mutates again immediately).
func (q *Queries) ListEventsForUser(ctx context.Context, arg ListEventsForUserParams) ([]ListEventsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForUser, arg.UserID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForUserRow{}
	for rows.Next() {
		var i ListEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Verb,
			&i.ActorID,
			&i.ActorName,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColor,
			&i.TargetType,
			&i.TargetID,
			&i.TargetLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
