// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package queries

import (
	"context"
	"database/sql"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, verb, actor_id, project_id, target_type, target_id, target_label, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID          string
	Verb        string
	ActorID     string
	ProjectID   sql.NullString
	TargetType  string
	TargetID    string
	TargetLabel string
	CreatedAt   int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Verb,
		arg.ActorID,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.TargetLabel,
		arg.CreatedAt,
	)
	return err
}

const listPersonalEventsForUser = `-- name: ListPersonalEventsForUser :many
SELECT
    e.id,
    e.verb,
    e.actor_id,
    u.name      AS actor_name,
    e.target_type,
    e.target_id,
    e.target_label,
    e.created_at
FROM events e
JOIN users u ON u.id = e.actor_id
WHERE e.project_id IS NULL
  AND e.actor_id = ?1
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?2
`

type ListPersonalEventsForUserParams struct {
	UserID string
	LimitN int64
}

type ListPersonalEventsForUserRow struct {
	ID          string
	Verb        string
	ActorID     string
	ActorName   string
	TargetType  string
	TargetID    string
	TargetLabel string
	CreatedAt   int64
}

func (q *Queries) ListPersonalEventsForUser(ctx context.Context, arg ListPersonalEventsForUserParams) ([]ListPersonalEventsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalEventsForUser, arg.UserID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalEventsForUserRow{}
	for rows.Next() {
		var i ListPersonalEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Verb,
			&i.ActorID,
			&i.ActorName,
			&i.TargetType,
			&i.TargetID,
			&i.TargetLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEventsForUser = `-- name: ListProjectEventsForUser :many
SELECT
    e.id,
    e.verb,
    e.actor_id,
    u.name      AS actor_name,
    e.project_id,
    p.name      AS project_name,
    p.color     AS project_color,
    e.target_type,
    e.target_id,
    e.target_label,
    e.created_at
FROM events e
JOIN users    u ON u.id = e.actor_id
JOIN projects p ON p.id = e.project_id
WHERE p.owner_id = ?1
   OR EXISTS (
        SELECT 1 FROM project_members m
        WHERE m.project_id = e.project_id AND m.user_id = ?1
   )
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?2
`

type ListProjectEventsForUserParams struct {
	UserID string
	LimitN int64
}

type ListProjectEventsForUserRow struct {
	ID           string
	Verb         string
	ActorID      string
	ActorName    string
	ProjectID    sql.NullString
	ProjectName  string
	ProjectColor sql.NullString
	TargetType   string
	TargetID     string
	TargetLabel  string
	CreatedAt    int64
}

func (q *Queries) ListProjectEventsForUser(ctx context.Context, arg ListProjectEventsForUserParams) ([]ListProjectEventsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectEventsForUser, arg.UserID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectEventsForUserRow{}
	for rows.Next() {
		var i ListProjectEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Verb,
			&i.ActorID,
			&i.ActorName,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectColor,
			&i.TargetType,
			&i.TargetID,
			&i.TargetLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
