// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package queries

import (
	"context"
	"database/sql"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET used_at = ?1,
    used_by = ?2
WHERE code_hash = ?3
  AND used_at IS NULL
  AND expires_at >= ?4
RETURNING project_id, role, issued_by
`

type ConsumeInviteParams struct {
	UsedAt   sql.NullInt64
	UsedBy   sql.NullString
	CodeHash string
	Now      int64
}

type ConsumeInviteRow struct {
	ProjectID sql.NullString
	Role      sql.NullString
	IssuedBy  string
}

// Atomically marks the invite used and returns its (project_id, role, issued_by).
// Returns no row if missing/expired/already-used. The caller passes the same
// timestamp for both `now` and `used_at`; we split them so sqlc infers distinct
// types (int64 for the expires_at comparison, NullInt64 for the SET).
func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (ConsumeInviteRow, error) {
	row := q.db.QueryRowContext(ctx, consumeInvite,
		arg.UsedAt,
		arg.UsedBy,
		arg.CodeHash,
		arg.Now,
	)
	var i ConsumeInviteRow
	err := row.Scan(&i.ProjectID, &i.Role, &i.IssuedBy)
	return i, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (code_hash, issued_by, project_id, role, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	CodeHash  string
	IssuedBy  string
	ProjectID sql.NullString
	Role      sql.NullString
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.CodeHash,
		arg.IssuedBy,
		arg.ProjectID,
		arg.Role,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :execrows
DELETE FROM invites
WHERE expires_at < ? OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredInvites, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
