// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type DeviceToken struct {
	ID         string
	Name       string
	TokenHash  string
	CreatedAt  int64
	LastSeenAt int64
}

type PairingCode struct {
	Code      string
	Name      string
	ExpiresAt int64
	Used      int64
}

type Todo struct {
	ID        string
	Title     string
	Done      bool
	CreatedAt int64
	UpdatedAt int64
}
