// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type Invite struct {
	CodeHash  string
	IssuedBy  string
	ProjectID sql.NullString
	Role      sql.NullString
	CreatedAt int64
	ExpiresAt int64
	UsedAt    sql.NullInt64
	UsedBy    sql.NullString
}

type Project struct {
	ID          string
	OwnerID     string
	Name        string
	Description sql.NullString
	Color       sql.NullString
	Archived    bool
	SortOrder   int64
	CreatedAt   int64
	UpdatedAt   int64
}

type ProjectMember struct {
	ProjectID string
	UserID    string
	Role      string
	AddedAt   int64
}

type Setting struct {
	Key   string
	Value string
}

type Todo struct {
	ID          string
	Title       string
	Description sql.NullString
	Done        bool
	ProjectID   sql.NullString
	CreatedBy   string
	CreatedAt   int64
	UpdatedAt   int64
}

type User struct {
	ID           string
	Name         string
	PasswordHash string
	Role         string
	CreatedAt    int64
}
