// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package queries

import (
	"context"
	"database/sql"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role, added_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = excluded.role
`

type AddProjectMemberParams struct {
	ProjectID string
	UserID    string
	Role      string
	AddedAt   int64
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.AddedAt,
	)
	return err
}

const countProjectsOwnedBy = `-- name: CountProjectsOwnedBy :one
SELECT COUNT(*) FROM projects WHERE owner_id = ?
`

func (q *Queries) CountProjectsOwnedBy(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsOwnedBy, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, owner_id, name, description, color, archived, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)
RETURNING id, owner_id, name, description, color, archived, sort_order, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string
	OwnerID     string
	Name        string
	Description sql.NullString
	Color       sql.NullString
	SortOrder   int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, name, description, color, archived, sort_order, created_at, updated_at
FROM projects
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT role
FROM project_members
WHERE project_id = ? AND user_id = ?
LIMIT 1
`

type GetProjectMembershipParams struct {
	ProjectID string
	UserID    string
}

// Returns the caller's role for the project, or no row if not a member.
func (q *Queries) GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectMembership, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT user_id, role, added_at
FROM project_members
WHERE project_id = ?
ORDER BY added_at ASC
`

type ListProjectMembersRow struct {
	UserID  string
	Role    string
	AddedAt int64
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(&i.UserID, &i.Role, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsVisibleTo = `-- name: ListProjectsVisibleTo :many
SELECT p.id, p.owner_id, p.name, p.description, p.color, p.archived, p.sort_order, p.created_at, p.updated_at
FROM projects p
WHERE p.owner_id = ?1
   OR EXISTS (
        SELECT 1 FROM project_members m
        WHERE m.project_id = p.id AND m.user_id = ?1
   )
ORDER BY p.sort_order ASC, p.created_at ASC
`

// All projects the user can see: owned + member-of.
func (q *Queries) ListProjectsVisibleTo(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsVisibleTo, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Archived,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :execrows
DELETE FROM project_members
WHERE project_id = ? AND user_id = ?
`

type RemoveProjectMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, description = ?, color = ?, archived = ?, sort_order = ?, updated_at = ?
WHERE id = ?
RETURNING id, owner_id, name, description, color, archived, sort_order, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string
	Description sql.NullString
	Color       sql.NullString
	Archived    bool
	SortOrder   int64
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Archived,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Archived,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
